bookers2/config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  root 'books#top'

  # post '/books' => 'books#create'

  resources :books
  resources :users, only: [:show, :edit, :update]

  get 'about' => 'books#about'

  get 'users' => 'users#users'

end

bookers2/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

bookers2/app/models/book.rb
class Book < ApplicationRecord
	validates :body, presence: true,
							 length: { maximum: 200 }

	belongs_to :user
	
end

bookers2/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
         validates :name, presence: true
         validates :name, presence: true, uniqueness: true,
         				  length: { minimum: 2, maximum: 20 }
         validates :introduction, length: { maximum: 50 }
  attachment :profile_image

  has_many :books

end

bookers2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email,:name,:introduction])
  end

  def after_sign_out_path_for resource
    root_path
  end

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

end

bookers2/app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!,only: [:new,:edit,:update,:destroy,:index] 
  # except: [:top]
  def top

  end

  def new

  	  @book = Book.new
  end

  def create

  		@book = Book.new(book_params)
      @book.user_id = current_user.id
  		if @book.save
  		  # redirect_to book_path(@book.id)
        flash[:success] = "投稿が成功しました。"
        redirect_to books_path, :flash => {:error => "errorが起きました"}
      else
        flash[:notice] = "TitleとOpinionを入力してください。もしくは、Opinionは２００文字以内でお願いします"
        redirect_to books_path, :flash => {:error => "errorが起きました"}
      end
  end

  def index

  	@books = Book.all

  	@book = Book.new

  end

  def show

  	@bookf = Book.find(params[:id])
    @book = Book.new


  end

  def edit

  	@book = Book.find(params[:id])

  end

  def update
  	  @book = Book.find(params[:id])
      @book.update(book_params)
      flash[:edit] = "編集しました。"
      redirect_to books_path
  end

  def about

  end

  def destroy
  	  @book = Book.find(params[:id])
      if @book.destroy
      flash[:destroy] = "削除しました。"
      redirect_to books_path, :flash => {:error => "errorが起きました"}
      else
      flash[:nodestroy] = "削除しませんでした"
      redirect_to books_path, :flash => {:error => "errorが起きました"}
  end
end

  		 private

    	def book_params
        	params.require(:book).permit(:title, :body)

    	end
end

bookers2/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find(params[:id])
  	@book = Book.new
  	# book.user_id = current_user.id
    # book.save
    # redirect_to book_path(book.id)
  	# @books = Book.all
  	@books = @user.books.page(params[:page])

  end

  def users
  	@book = Book.new
  	@users = User.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if@user.update(user_params)
    redirect_to user_path(@user.id)
    else
	flash[:notice] = "introductionは50文字以内でお願いします"
    redirect_to edit_user_path, :flash => {:error => "errorが起きました"}
    end
  end

	private
		def user_params
		    params.require(:user).permit(:name, :profile_image, :introduction)

		end
end

bookers2/app/helpers/application_helper.rb
module ApplicationHelper
end

bookers2/app/helpers/books_helper.rb
module BooksHelper
end

bookers2/app/helpers/users_helper.rb
module UsersHelper
end

bookers2/app/views/books/about.html.erb
<div class="body">
      <div class="container">
        
        <p id="notice"></p>
      
      	<h1>Welcome to <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>!</h1>


      </div>
    </div>

bookers2/app/views/books/edit.html.erb
<div class="body">
      <div class="container">
          
        
        <p id="notice"></p>
      
        <div class="row">
  <h1>Editing Book</h1>
  <div class="col-xs-3">
  </div>

  <div class="col-xs-9">
   <%= form_for(@book) do |f| %>
  <div class="field row">
    <label for="book_title">Title</label>
    <%= f.text_field :title, class: "col-xs-12" %>
  </div>

  <div class="field row">
    <label for="book_opinion">Opinion</label>
    <%= f.text_area :body, class: "col-xs-12"%>
  </div>

  <div class="actions row">
     <%= f.submit 'Update Book', class: "btn btn-primary col-xs-12" %>
  </div>
     <%= link_to "Show", book_path %> |
     <%= link_to "Back", books_path %>
  </div>
  <% end %>
</div>
      </div>
    </div>

bookers2/app/views/books/index.html.erb
<div class="body">
  <div class="container">
    <p id="notice"></p>
    <div class="row">

     <div class="col-xs-3">
      <h2>User info</h2>
        <table class="table">
          <tbody><tr></tr>
          <% if current_user.profile_image.present? %>
            <%= attachment_image_tag current_user, :profile_image, :fill,100, 100, format: 'jpeg' %>
          <% else %>
            <p><%= image_tag "no_image.jpg", :width=>"100px", :height=>"100px" %></p>
          <% end %>
          <tr>
            <th>name</th>
            <th><%= current_user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= current_user.introduction %></th>
          </tr>
        </tbody>
      </table>

      <div class="row">
        <%= link_to "", edit_user_path(current_user.id), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench"%>
      </div>


      <h2>New book</h2>
    <%= form_for(@book) do |f| %>
  <div class="field row">
    <label for="book_title">Title</label>
    <%= f.text_field :title, class: "col-xs-12" %>
  </div>

  <div class="field row">
    <label for="book_opinion">Opinion</label>
    <%= f.text_area :body, class: "col-xs-12" %>
  </div>

  <div class="actions row">
    <%= f.submit 'Create Book', class: "btn btn-primary col-xs-12" %>
  </div>
  <div><%= flash[:notice] %></div>
  <div><%= flash[:success] %></div>
  <% end %>
  <div><%= flash[:destroy] %></div>
  <div><%= flash[:nodestroy] %></div>
  <div><%= flash[:edit] %></div>
  <div><%= flash[:noedit] %></div>

  </div>

  <div class="col-xs-9">
    <h2>Books</h2>

        <table class="table table-hover table-inverse">
      <thead>
        <tr> 
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @books.each do |book| %>
        <tr>
          <td><%= link_to user_path(book.user) do %>
            <%= attachment_image_tag book.user, :profile_image, :fill,40,40, format: 'jpeg' %>
      <% end %>
              
            </td>
            <td><%= link_to book_path(book.id) do %>
              <%= book.title %>
              <% end %>
              </td>
              <td><%= book.body %></td>
        </tr>
          <% end %>
      </tbody>
    </table>
  </div>
</div>
      </div>
    </div>

bookers2/app/views/books/new.html.erb
<h2>New book</h2>
 <%= form_for(@book) do |f| %>

	<h4>title</h4>
    <%= f.text_field :title %>

    <h4>body</h4>
    <%= f.text_area :body %>

    <%= f.submit 'Create Book' %>
    <div><%= flash[:notice] %></div>

<!-- test -->

bookers2/app/views/books/show.html.erb
<div class="body">
      <div class="container">
          
        
        <p id="notice"></p>
      
        <div class="row">
  <div class="col-xs-3">
    <h2>User info</h2>
    <table class="table">
      <tbody><tr></tr> 
        <% if @bookf.user.profile_image.present? %>
          <%= attachment_image_tag @bookf.user, :profile_image, :fill,100, 100, format: 'jpeg' %>
        <% else %>
          <p><%= image_tag "no_image.jpg", :width=>"100px", :height=>"100px" %></p>
        <% end %>
      <tr>
        <th>name</th>
        <th><%= @bookf.user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= @bookf.user.introduction %></th>
      </tr>
    </tbody></table>
    <div class="row">
      <% if @bookf.user == current_user %>
      <%= link_to "", edit_user_path(@bookf.user.id), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
       <% end %>
    </div>

    <h2>New book</h2>
    <%= form_for(@book) do |f| %>
  <div class="field row">
    <label for="book_title">Title</label>
    <%= f.text_field :title, class: "col-xs-12" %>
  </div>

  <div class="field row">
    <label for="book_opinion">Opinion</label>
    <%= f.text_area :body, class: "col-xs-12" %>
  </div>

  <div class="actions row">
    <%= f.submit 'Create Book', class: "btn btn-primary col-xs-12" %>
  </div>
  <% end %>
  <div><%= flash[:notice] %></div>
  </div>
  

  <div class="col-xs-9">
    <h2>Book detail</h2>
    <table class="table">
      <tbody>
        <tr>
          <td><%= attachment_image_tag @bookf.user, :profile_image, :fill,40,40, format: 'jpeg' %><br>
          <%= @bookf.user.name %></td>
        <td><%= @bookf.title %></td>
        <td><%= @bookf.body %></td>
        <td>
    <% if @bookf.user == current_user %>
    <%= link_to "Edit", edit_book_path(@bookf.id) %>
    <% end %>
    </td>
    <td>
    <% if @bookf.user == current_user %>
    <%= link_to "Destroy", book_path(@bookf.id), method: :delete, "data-confirm" => "Are you sure?" %>
    <% end %>
  
    </td>

      </tr>
    </tbody></table>

  </div>
</div>
      </div>
    </div>

bookers2/app/views/books/top.html.erb
<div class="body">
      <div class="container">
        
        <p id="notice"></p>
      
        <div class="row">
  <div class="top-message col-md-offset-3 col-md-6">
    <h1>welcome to <span class="glyphicon glyphicon-book"><strong>Bookers</strong>  !!</span></h1>
          <p>In  <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>, </p>
          <p>you can share and exchange  your opinions , inpressions , and emotions</p>
          <p> about varioius books!</p>

    <div class="btn-wrapper">
      <div class="row">
         <p><%= link_to "Log In", new_user_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1" %></p>
      </div>
      <div class="row">
        <p><%= link_to "Sign Up", new_user_registration_path, class: "btn btn-success col-xs-10 col-xs-offset-1" %></p>
      </div>
    </div>
            
  </div>
</div>
        
      </div>
    </div>

bookers2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav class="nav navbar-nav navbar-left">
      <span class="glyphicon glyphicon-book">Bookers</span>
    </nav>
    <nav>
      <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
      <li>
        <%= link_to 'Home', user_path(current_user.id) %>
      </li>
      <li>
        <%= link_to "Users", users_path %>
      </li>
      <li>
        <%= link_to 'Books', books_path %>
      </li>
      <li>
       <%= link_to 'logout',  destroy_user_session_path, method: :delete %>
      </li>
    <% else %>
      <li>
        <%= link_to "Home", root_path %>
      </li>
      <li>
        <%= link_to "about", about_path %>
      </li>
      <li>
        <%= link_to "sign up", new_user_registration_path %>
      </li>
      <li>
        <%= link_to "login", new_user_session_path %>
      </li>
    <% end %>
      </ul>
    </nav>
  </div>
</header>

    <%= yield %>

    <footer>
      <div class="container">
        <div class="row">
          <div class="col-xs-3 col-xs-offset-9">
            <p>CopyRight @BA-SHOW</p>
          </div>
        </div>
      </div>
    </footer>


  </body>
</html>

bookers2/app/views/users/edit.html.erb
<div class="body">
      <div class="container">
        
        <p id="notice"></p>
      
        <h2>User info</h2>

<%= form_for(@user) do |f| %>

  <div class="field">
    <label for="user_name">Name</label>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <label for="user_image">Image</label>
     <%= f.attachment_field :profile_image %>
  </div>

  <div class="field">
    <label for="user_introduction">Introduction</label>
   <%= f.text_area :introduction %>
  </div>

  <div><%= flash[:notice] %></div>

  <div class="actions">
    <%= f.submit 'Update User' %>
  </div>
  <% end -%>
      </div>
    </div>

bookers2/app/views/users/show.html.erb
<div class="body">
  <div class="container">
    <p id="notice"></p>
    <div class="row">

      <div class="col-xs-3">
        <h2>User info</h2>
        <table class="table">
          <tbody><tr></tr>
          <% if @user.profile_image.present? %>
            <%= attachment_image_tag @user, :profile_image, :fill,100, 100, format: 'jpeg' %>
          <% else %>
            <p><%= image_tag "no_image.jpg", :width=>"100px", :height=>"100px" %></p>
          <% end %>
          <tr>
            <th>name</th>
            <th><%= @user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= @user.introduction %></th>
          </tr>
        </tbody>
      </table>

      <div class="row">
        <%= link_to "", edit_user_path(@user.id), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench"%>
      </div>


      <h2>New book</h2>
      <div class="field row">
        <%= form_for(@book) do |f| %>
          <label for="book_title">Title</label>
            <%= f.text_field :title, class: "col-xs-12" %>
      </div>

      <div class="field row">
        <label for="book_opinion">Opinion</label>
          <%= f.text_area :body, class: "col-xs-12" %>
      </div>

      <div class="actions row">
        <%= f.submit 'Create Book', class: "btn btn-primary col-xs-12" %>
      </div>
      <% end -%>
    </div>

  <div class="col-xs-9">
    <h2>Books</h2>

      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <% if book.user.profile_image.present? %>
                    <%= attachment_image_tag current_user, :profile_image, :fill,100, 100, format: 'jpeg' %>
                <% else %>
                    <%= image_tag "no_image.jpg", :width=>"40px", :height=>"40px"  %>
                <% end %>
              </td>
                <td><%= book.title %></td>
                <td><%= book.body %></td>
                <td>
                  <% if book.user == current_user %>
                    <%= link_to "Edit", edit_book_path(book.id) %>
                  <% end %>
                </td>
                <td>
                  <% if book.user == current_user %>
                  <%= link_to "Destroy", book_path(book.id), method: :delete, "data-confirm" => "Are you sure?" %>
                  <% end %>
                </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
</div>

bookers2/app/views/users/users.html.erb
<div class="body">
      <div class="container">
          
        
        <p id="notice"></p>
      
        <div class="row">
  
  <div class="col-xs-3">
    <h2>User info</h2>
    <table class="table">
      <tbody><tr></tr>
        <% if current_user.profile_image.present? %>
          <%= attachment_image_tag current_user, :profile_image, :fill,100, 100, format: 'jpeg' %>
        <% else %>
          <p><%= image_tag "no_image.jpg", :width=>"100px", :height=>"100px" %></p>
        <% end %>
      <tr>
        <th>name</th>
        <th><%= current_user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= current_user.introduction %></th>
      </tr>
    </tbody></table>
    <div class="row">
     <%= link_to "", edit_user_path(current_user.id), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
    </div>

    <h2>New book</h2>
    <%= form_for(@book) do |f| %>
  <div class="field row">
    <label for="book_title">Title</label>
    <%= f.text_field :title, class: "col-xs-12" %>
  </div>

  <div class="field row">
    <label for="book_opinion">Opinion</label>
    <%= f.text_area :body, class: "col-xs-12" %>
  </div>

  <div class="actions row">
    <%= f.submit 'Create Book', class: "btn btn-primary col-xs-12" %>
  </div>
  <% end %>
  <div><%= flash[:notice] %></div>

  </div>

  <div class="col-xs-9">
    <h2>Users</h2>

    <table class="table">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><% if user.profile_image.present? %>
          <%= attachment_image_tag user, :profile_image, :fill,100, 100, format: 'jpeg' %>
        <% else %>
          <p><%= image_tag "no_image.jpg", :width=>"100px", :height=>"100px" %></p>
        <% end %></td>
        <td><%= user.name %></td>
        <td><%= link_to "Show", user_path(user.id) %></td>
      </tr>
      <% end %>
  </tbody>
</table>

  </div>

</div>
      </div>
    </div>